### ISSUE TITLE
Create integration tests for listing active timetables on given operating day

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#1094]
The `get_vehicle_services_for_date` SQL function does not have integration tests yet. Tests should be done in hasura repository.

 However a few things need to be refactored before this could be done so:
- [ ] should fork integration tests that they work both with generic and with hsl version of the datamodel
- [ ] refactor the dataset module for integration tests to be more flexible
- [ ] create the integration tests for the `get_vehicle_services_for_date` function

**Comment by HenrikHartiala** [comment]
This function mentioned here was initially used for vehicle schedule page, but was replaced with get_vehicle_schedules_on_date on this commit (and that function also already has integration tests): 
Add new fetching logic to timetable page	bdc508f3	Henrik Hartiala <henrik.hartiala@vincit.fi>	27. Jul 2023 at 10.58

I did not remove the function mentioned in this ticket, because was not sure if there were some other use cases for this function. So currently we could rethink the need of this function.
If we see no use for this function, we could remove this function and also remove this test ticket. I will open a slack thread about this and then do the necessarities.

**Comment by HenrikHartiala** [comment]
After minor review it seems there is no further use for this function and can be removed. So I'm closing this ticket as not planned, and here is the ticket for the removal of the function: https://github.com/HSLdevcom/jore4/issues/1437
