### ISSUE TITLE
As a scrum team member I wish to have a see a user interface on which I can browse for relevant tickets easier than the basic GitHub UI || M

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#114]

**Comment by pallost** [comment]
Suggestion to try Zenhub first as it integrates into GitHub and is not a separate tool like JIRA/Trello/ClubHouse, etc

**Comment by pallost** [comment]
Observations about Zenhub, compared to Github kanban board

👍 it integrates into Github instead of being a standalone tool by itself, so we expect it to enable better insight for externals
👍 it has a roadmap feature
👍 it has sprints

👎 it does not seem to synchronize kanban board between github and zenhub, only the issues
👎 even the kanban board columns are not synchronized
👎 this also means that the priority of the tickets are also not synchronized

**Comment by jpeuralinna** [comment]
Azure Boards:
- boards cannot be synced with github boards
+ can be made visible for "outsiders" so it doens't require registration to access 
+ better ui and filtering than githubs
+ has epics and sprints
+ tickets can easily be assigned to specific sprints (current and upcoming)
+ easy creation of burndown and other charts
+ can be connected to github repositories, so that commits and pull requests point to specific tickets in azure.

Overall better tool for project management than github, but it cannot be synced with github boards. So would require us using only Azure Boards. Moving to Azure boards would propably be unnecessary work, unless we would also use other Azure Devops tools (repos, pipelines, test plans, artifacts).
