### ISSUE TITLE
Study if we can utilize Entur's frontend (Abzu) for stop registry

### ISSUE THREAD

**Issue by teittla** [HSLdevcom/jore4#1194]
Entur has an open source frontend for Tiamat called Abzu. Study lightly if we can utilize same code for our stop registry. Consider different scenarios such as:
1) Use Abzu as such
2) Use some parts for Jore4 UI and API

See https://github.com/entur/abzu and https://stoppested.entur.org/

Note: Depends on the decision whether we will use Tiamat (a-rinki 16.3.). Relates to #1185

**Comment by eleksi** [comment]
- There is some TypeScript but also a lot of JavaScript.
- MaterialUI components.
- GraphQL queries could be utilized
- Redux Toolkit used at least some
- Supports translations
- At least part of styles (logo, colors) easily customizable

**Comment by tk-vincit** [comment]
I checked Abzu repository + codebase briefly and tried to guess how well it would suite on JORE4's needs from _technical_ perspective. Probably the biggest question is "does it do what we need?" and we should start with that. Anyway:

- License: `Licensed under the EUPL, Version 1.2 or – as soon they will be approved by
the European Commission - subsequent versions of the EUPL`. JORE4 is also licensed with EUPL 1.2, so they should be combatible from that perspective.
- Initial commit 7 years old
- No major red flags in codebase at first look. Yes, some code is old and written as JS, so typings are not perfect. Codebase is not new, so old React syntax with class components and lifecycle methods instead of function components and hooks is used too. Some redux code implemented with redux-toolkit's slices, some with more traditional approach. Not an issue by itself, but should be noted in case if merging some code from Azbu to Jore is at the table.
- Some files seems to be pretty long
- Code seems to be organized punctually at least on directory level
- Most important documentation (how to start the app locally + how to run tests) seems to be in README.
- Detailed documentation not available (at least not within the repository itself). E.g. code conventions or desing principles have to be deduced from the code itself
- Libraries seem to be at least mostly up-to-date. Renovatebot seems to be enabled.
- UI starts locally out-of-the box after cloning the repository by running `npm install && npm start` (as documented in README)
- At least some tests & CI pipeline with basic checks included
- 14 test suites with 72 of total tests, all seems to be passing at least locally. No idea how well they cover actual use cases. The safe assumption is that probably not well enough, but anyway they give some safety if we have to modify the codebase for our needs.
- Project formatted with `prettier``
- No `eslint`/`tslint` used.
- Styled with `css` files + inline `style` tags
- It should be checked individually if Abzu meets our accessibility recuirements or no.
- Finnish language not supported, but seems like it can be added very easily

I would consider trying Abzu as is as first option, and evaluate if it would fit our needs. In best case we could use it as independent module with little or no modifications. As "official"(?) Tiamat UI it is very likely that Abzu works well with Tiamat and thus using it might save lots of work from us. 

In fact one major question is if timetable registry should work as independent module with independent UI, or should it rather be implemented within JORE4 UI. If we want implement timetable registry within JORE4 UI, then things come a bit trickier. Probably it doesn't make sense to just copypaste code to JORE4, but at least Abzu implementation could work as some kind of benchmark.

We could also consider to contribute to Abzu development, especially if it requires changes to fill our needs and if those changes would be useful also for third parties. In that case it would make sense to try contact Abzu maintainers and discuss about this possibility.

**Comment by pallost** [comment]
A few additions by myself:
- we haven't yet assessed if Tiamat is actually capable of fulfilling all the needs of HSL's stop registry. If we see that only small changes/additions are necessary, then we could get away with using Abzu as a frontend. If major changes need to be applied to Tiamat, it feels pointless to also keep on patching Abzu.
- the JORE4 design in Figma is customized for HSL's needs. If it's decided that we go with Abzu, many changes might need to be applied to tweak it for HSL's needs.
- If it's decided that we go with the Figma design, a really tiny amount of Abzu's code could be reused, but could be useful at least as a reference on how to communicate with Tiamat.
