### ISSUE TITLE
Fix bug in timetables validity period

### ISSUE THREAD

**Issue by eleksi** [HSLdevcom/jore4#1250]
NOTE FOR DESIGN: We should consider whether we even have to show a validity period here, as the the "cards" and other UI components shown here already display validity period. See below for context.

Validity period displayed for route accordion in timetables view is not valid. It does not take into account which timetables are active for given observation date (day type).

In the first picture one can see, that the validity periods do not match in the route accordion and the day type card.

![Image](https://user-images.githubusercontent.com/51695324/234828168-f0a3fd6f-b631-43c7-a680-26fc7b5d1d63.png)

In the second picture we can see they match, as the 1.4.-30.4. timetable is also visible. 

![Image](https://user-images.githubusercontent.com/51695324/234828742-1b531a38-a2b6-4201-a9e7-27d0e6eb9116.png)

So it seems that route accordion does not take into account which timetables are visible when calculating the validity period, and that should be fixed. The function that calculates this is `getTimetableValidity`, but it has to be decided whether we want to filter the timetables in the function or outside.

To reproduce: start dependencies with dumps and seeds (scripts/setup-dependencies-and-seed.sh), go to route 641 timetables and select observation date in April 2023.

**Comment by HenrikHartiala** [comment]
So this might need more spesification. This is partly done in #1158 where we show multiple day types at the same time and we calulate the narrowest validity period. But we also discussed that what is exactly the functionality of this "combined validity period" because we only show the narrowest combined validity for the schedules that are shown. But it does not take in to consideration anything that happens after this day. 
So after the #1158 is moved in to main, it means that the combined validity means a period in which these schedules are valid, but it does not mean that during that validity period, these are the only ones valid.

And to the initial question, how should this validity period actually work and does it bring any value? If we want it to show a period in which these schedules AND ONLY these schedules are valid, then we need to first check what is the narrowest validity period (done) and then we need to fetch all schedules during that period to see when some schedule changes.
