### ISSUE TITLE
As a planning assistant I want to modify a route temporarily, with stop times staying unmodified along the route

### ISSUE THREAD

**Issue by ossiberg** [HSLdevcom/jore4#136]
Temporarily = priority is not the basic priority

Stop times staying unmodified = nowadays with jore3 this is quite tricky, typically requires making a new timetables with Hastus, which is labor intensive.

Preferably this could be managed in a way that LIJ would not require new "kaaviot" (what is this in English? Probably not "vehicle schedules")

--

A) Current non-MVP design allows [copying a base route to create a modified temporary route](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2041%3A76521) (Figma). Route extension or truncation should be implemented in a way that preserves unmodified stops. The user [is notified](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=3036%3A208173) when timetables are interpolated.

B) If copying a based route is not yet implemented (MVP), the user can edit a base version and and save it as a new temporary version. The user is notified as in A)

If creating a temporary detour instead of an extension, the stop times before the detour should also be preserved.

**Comment by juhakolari** [comment]
Current design allows [copying a base route to create a modified temporary route](https://www.figma.com/file/ImSTkCqQn0nhVUtMcUm41P/JORE-4.0-UX?node-id=2041%3A76521)Figma). Route extension or truncation should be implemented in a way that preserves unmodified stops. 

If creating a temporary detour instead of an extension, the stop times before the detour should also be preserved.
