### ISSUE TITLE
Stop and passing times are sometimes sorted incorrectly

### ISSUE THREAD

**Issue by Leitsi** [HSLdevcom/jore4#1547]
Example case, two issues here:
- the first stop `H2201` is sorted last
~~- times in stop `H2204`  are sorted incorrectly: 27 is after 47~~ (Fix in #1617)

![Image](https://github.com/HSLdevcom/jore4/assets/3958530/d7ad1feb-8b5f-4e2b-bb47-39dc9a492530)

Could not find the exact conditions that reproduce this.
Seems to happen at least after combining timetables, but not every time, not even when doing same import with same dataset from scratch (truncating DB in between).

Research if duplicate with #1617

**Comment by HenrikHartiala** [comment]
Okay, so this part `times in stop H2204 are sorted incorrectly: 27 is after 47` is fixed within pull request linked to #1617, this applied only to the last stops. 
But still need to research why e.g. in this screenshot the last stop is sorted as second to last.

I will update the description so that the mentioned issue is fixed.
