### ISSUE TITLE
As a Developer, I want to automate issues so that when a pull request gets merged, the issue automatically gets to Reviewer approved

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#265]

**Comment by jschummer** [comment]
Having taken a look at this, it seems that
1. Automation only works for PR:s which are created in the same repository as the issue
2. It is unclear if this works with reviewable.io, but I didn't check too carefully because of 1.

Can this be closed as "won't fix" or similar or is there something which I haven't taken into account @pallost ?

**Comment by haphut** [comment]
@jschummer I made an org-level [GitHub project](https://github.com/orgs/kahmalo/projects/1), a separate repository for [issues](https://github.com/kahmalo/github-project-test-issue-repo/issues) and a repository for [PRs](https://github.com/kahmalo/github-project-test-pr-repo/pulls).

The board automation for the column "Done" was to move issues there when closed and to move PRs there when merged or closed. I created [an issue for testing](https://github.com/kahmalo/github-project-test-issue-repo/issues/1) the automation and added the issue onto the board. Then I created [a PR for closing](https://github.com/kahmalo/github-project-test-pr-repo/pull/1) the issue.

When I merged the PR, the issue moved into the column Done in Chromium immediately.

So what caused the difference in our experiences? Some ideas:
- I think Firefox does not update the board without a manual refresh.
- I have ultimate rights to that organization.
- The trigger words "Fixes kahmalo/github-project-test-issue-repo#1" I wrote into the PR description, not into a git commit description.

**Comment by jschummer** [comment]
Ok, thanks for the comment and for checking @haphut .

From the [manual](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (yes, for once I checked the README ;-) ) I got the impression that the PR and issue must be on the same repo for this to work.

Having just double-checked, I might have been wrong, and this is needed only for some scenarios / certain automation.

I'll perform two real-life tests with our real issue board, one with github review and one with reviewable. I'll comment here how they go.

**Comment by jschummer** [comment]
First test concluded with a negative result: [This ticket](https://github.com/HSLdevcom/jore4/issues/83) did not move when [this PR](https://github.com/HSLdevcom/jore4-deploy/pull/27) was accepted. However, the magic words ("fixes XXX") were added as a comment after the PR had been created.

Will try with a second PR, to whose description I'll add the magic words right when it is created.

**Comment by jschummer** [comment]
This seems to require github actions. Github's builtin board column automation does not seem to work for issues with linked PRs.

As pointed out by @haphut , the builtin board column automation seems to be meant only for PRs which are themselves tracked on the board, not for issues which are linked to PRs.

Since this feature may not bring much additional value to the daily development process, I'll close this issue now.

Let's take this back into another sprint and solve it using github actions if we decide so later.
