### ISSUE TITLE
As a developer I want jore3 importer's SQL user's permissions to jore4 main database to be set

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#385]
- [x] add CRUD permissions to schemas used by jore3 importer (service_pattern, journey_pattern, internal_service_pattern, internal_route ja route)
- [x] remove unused import_jore3 schema
- [x] remove unused auth_session schema

**Comment by pkainulainen-vincit** [comment]
The problem is that the importer needs to generate jOOQ query classes from the Jore 4 database and unfortunately the jOOQ documentation doesn't specify the minimum permissions which are required by code generation.

More details:

https://groups.google.com/g/jooq-user/c/mBXLTcQspNc
https://github.com/jOOQ/jOOQ/issues/10820

In other words, if we still want to determine the minimum permissions which work, we have to use trial and error which is quite slow (and frustrating).

**Comment by pallost** [comment]
In my opinion we could just use the admin credentials for jooq generation as it only happens in our development environment

**Comment by pkainulainen-vincit** [comment]
If that's the case, we can use admin for code generation and configure the importer application to use its own user. The importer's database user requires `SELECT`, `INSERT`, and `DELETE` privileges to all tables found from these schemas: `service_pattern`, `journey_pattern`, `internal_service_pattern`,  `internal_route`, and `route`.

**Comment by pallost** [comment]
added this as a subtask. Added another subtask to clear unused jore3 and internal_jore3 schemas from jore4 database
