### ISSUE TITLE
Research how to make route drawing more user-friendly 

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#575]
Avoid failure when route starts on a different infra link than the first bus stop.

Route generally starts from a bus stop. We don't have to support other use cases now.

**Comment by jschummer** [comment]
Most cases (if not all) of the route starting from a stop, which does not reside on the route's first link, seem to originate from a stop residing on a different link than what the user is led to believe.

The current frontend implementation works like this:
- frontend fetches the route links from the map-matching backend
- frontend fetches all stops along the route
- the first stop is selected to be the route's starting stop point
- the last stop is selected to be the route's ending stop point

Therefore, if the user draws a route, which seemingly starts at a certain stop point, chances are that stop point is in fact not on a link included in the route. This can been reproduced easily by placing a stop point at a node (e.g. next to crossroads) and drawing a route starting from that stops.

In order to avoid these situations, it might be good if
- the user could manually choose the link a stop resides on or
- display the link the stop resides on when the stop is selected (as suggested by @pallost )
