### ISSUE TITLE
Fix "route validity within line validity" triggers that they also include the starting/ending days of the range

### ISSUE THREAD

**Issue by pallost** [HSLdevcom/jore4#683]
New notes: Datamodel and UI don't work seamlessly together at the moment. Might relate to the fact that liikennöintivuorokausi is different.

Test with the night lines, to see if that fixes the problem.

Currently cannot set the route to start/end on the exact same days with the line as the range is exclusive. Should fix the '< >' relations to be the inclusive '>= <='

- [ ] should fix the check_line_validity_against_all_associated_routes trigger to include the ends of the time range
- [ ] should fix the check_route_validity_is_within_line_validity trigger to include the ends of the time range
- [ ] should create integration test for testing that the validation functions properly (should probably also test the behavior with open-ended internals)

**Comment by jschummer** [comment]
This might need some more investigation and not be as straightforward as it seems. The '<' and '>' comparisons in the trigger functions are used to determine the cases when the error is raised, so they should be the right way around.

Also, the following tests can (and maybe should) be added to `integration-test/tests/data-integrity/line-routes/validity-period/update-route.spec.ts`, which will succeed:

`  describe("with a fixed validity start time of 1 ms prior to the validity time of the line", () => {
    const toBeUpdated = {
      validity_start: new Date(lines[1].validity_start!.getTime() - 1),
    };

    shouldReturnErrorResponse(routes[1], toBeUpdated);
    shouldNotModifyDatabase(routes[1], toBeUpdated);
  });

  describe("with a fixed validity start time equal to the validity time of the line", () => {
    const toBeUpdated = {
      validity_start: lines[1].validity_start,
    };

    shouldReturnCorrectResponse(routes[1], toBeUpdated);
    shouldUpdateCorrectRowInDatabase(routes[1], toBeUpdated);
  });
`

**Comment by jschummer** [comment]
The tests mentioned above have been added to the integration tests and they succeed. This is a strong indication that the constraint mentioned works as planned and that the error seen originates from another problem.

Because our UI can only display "whole day" timestamps, a possible reason may be that the database contains a line entity, whose validity period starts at e.g. "2020-01-01 03:00", which is displayed as "2020-01-01" in the UI. This would cause that the user would not be able to create a route under that line, whose validity period is set to start at "2020-01-01", which is expanded to "2020-01-01 00:00" and is before the line validity start of "2020-01-01 03:00".

Investigating, if this could explain the seen problem and how it could be fixed / mitigated.
