### ISSUE TITLE
As a user, I'd like the map to zoom in on the selected route when entering the map view

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#841]
Currently, the map always shows Hki railway station, which requires the user to actively look for the route to be edited using zoom.

This could be easier with upgraded version of `react-map-gl`, so depends on #657.

Ideally the beginning of the route is fetched and the camera (the part shown in the map) is placed according to that.

**Comment by HenrikHartiala** [comment]
Currently we can't upgrade `react-map-gl` to v7 but the map should already be positioned to the selected route. To achieve this, we should not use that much effort for this as it might be very trivial to accomplish once we do have the `react-map-gl` updated.

For the time being, I suggest that we simply position the map to the start of the selected route, by using `route_shape` and picking the first coordinates we find there.

In the implementation there is currently one issue, which is that the route_shape might come as `MultiLineString` from the database instead of the `LineString` which is the only type that UI recognizes for `route_shape`. The MultiLineString is a possible outcome of the psql function which calculates `the route_shape`. And the combination of 
```
ST_LineMerge(
    ST_Collect(...))
```
There is at least two different ways of dealing with this.
1. Use a temporary check in frontend to check the type of `route_shape`. This can be done by checking `route_shape.type` which in this case would be either `LineString` or `MultiLineString` and then we cast the route_shape to correct type and get the first coordinate we find.

2. We can change the route_shape calculating psql function to use `ST_MakeLine` instead of the combination of `ST_LineMerge and ST_Collect` and it would always (?) return the `route_shape` as `LineString`. For me there are at least a couple of things that are uncertain for me in this implementation.
  2a. I'm not that familiar with this ST_MakeLine, so is there any downside for this? 
  2b. Even if we would go with the `1.` implementation, would we still want to replace the function implementation to use `ST_MakeLine`?

**Comment by HenrikHartiala** [comment]
Drafts of these changes are ready, but currently we decided to wait until the demo is done.
