### ISSUE TITLE
UI attaches same stop point label multiple times to route when route is modified

### ISSUE THREAD

**Issue by jschummer** [HSLdevcom/jore4#889]
Steps to reproduce:
1. Create 1 stop with label "A" and 2 stops, both of which having label "B" (different priority)
2. Create a route stopping at both "A" and "B"
3. Observe database content

Expected result:
- DB contains journey pattern with 2 rows: "A" and "B"

Actual result:
- DB contains journey pattern with 3 rows "A", "B", "B"

Alternative steps to reproduce:
1. Create 1 stop with label "A" and 1 stop with label "B"
2. Create a route stopping at both "A" and "B"
3. Observe database content, DB contains journey pattern with 2 rows: "A" and "B"
4. Modify the route geometry, e.g. extend the route
5. Save the modified route
6. Observe database content

Expected result:
- DB contains journey pattern with 2 rows: "A" and "B"

Actual result:
- DB contains journey pattern with 3 rows "A", "B", "B"

**Comment by eleksi** [comment]
Please note that currently UI allows adding only stops that are shown in the map to a route. By default, the map shows the highest priority instance of each stop, when default map stop filters are selected. 

By changing stop filters, multiple instances of the same stop can be shown, and then adding multiple instances of a stop to a route could be (maybe) possible. Please check this bug especially with modified stop filters.

**Comment by HenrikHartiala** [comment]
This should be already fixed in UI. We use this filtering which removes consecutive stop labels. So even if we have stop "B" once as Standard priority, 10meters away we have stop "B" with Temporary priority and then we have both stops visible on map when drawing the route -> it will add the stop only once.

[#892](https://github.com/HSLdevcom/jore4/issues/892) Is a ticket to also prevent this on database. But currently this is handled already in the UI.

From useExtractRouteFromFeature.ts:
```
  /**
   * Removes all duplicate labeled consecutive stops from the list
   * This is used for example removing different versions of stops from the
   * journey pattern list where only the labels are shown
   */
  const filterDistinctConsecutiveRouteStops = useCallback(
    <TStop extends Pick<ServicePatternScheduledStopPoint, 'label'>>(
      stops: TStop[],
    ) => stops.filter((stop, index) => stops[index - 1]?.label !== stop.label),
    [],
  );
```
